### ISSUE TITLE
I am getting java.lang.NullPointerException on Android 10 

### ISSUE THREAD

**Issue by 04tushar** [g123k/flutter_plugin_device_apps#61]
java.lang.NullPointerException: 
  at m.a.a.b.e (DeviceAppsPlugin.java:1)
  at m.a.a.b.a (DeviceAppsPlugin.java:1)
  at m.a.a.b$b.run (DeviceAppsPlugin.java:1)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:919)

And 

java.lang.NullPointerException: 
  at n.a.a.b.e (DeviceAppsPlugin.java:1)
  at n.a.a.b.a (DeviceAppsPlugin.java:1)
  at n.a.a.b$b.run (DeviceAppsPlugin.java:1)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:919)

**Comment by g123k** [comment]
Thanks for the report.
Do you have the "un-obfuscated" stack trace please?

**Comment by 04tushar** [comment]
Pleae check this:

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.content.Context.getPackageManager()' on a null object reference
       at fr.g123k.deviceapps.DeviceAppsPlugin.getInstalledApps(DeviceAppsPlugin.java:131)
       at fr.g123k.deviceapps.DeviceAppsPlugin.access$000(DeviceAppsPlugin.java:44)
       at fr.g123k.deviceapps.DeviceAppsPlugin$2.run(DeviceAppsPlugin.java:120)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)

**Comment by 04tushar** [comment]
Any update ?

**Comment by g123k** [comment]
Will be fixes in 1.2.1 release
